version: '3'
services:

  payment-page-service:
    image: payment-page-service:0.0.1-SNAPSHOT
    container_name: payment-page-service
    ports:
      - "8082:8082"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      spring.datasource.url: jdbc:mysql://mysql:3306/payment_page
    depends_on:
      - mysql
      - eureka

  player-benefits-service:
    image: player-benefits-service:0.0.1-SNAPSHOT
    container_name: player-benefits-service
    ports:
      - "8081:8081"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      spring.aerospike.host: aerospike
    depends_on:
      - aerospike
      - eureka

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
    depends_on:
      - eureka

  eureka:
    image: eureka:0.0.1-SNAPSHOT
    container_name: eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8761/actuator/health 2>&1 | grep UP || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_page

  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike
    ports:
      - "3000-3002:3000-3002"
    environment:
      NAMESPACE: payments
