version: '3'
services:

  payment-page-service:
    hostname: payment-page
    image: payment-page-service:0.0.1-SNAPSHOT
    container_name: payment-page-service
    ports:
      - "8082:8082"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/payment_page
      PLAYER_BENEFITS_URI: http://player-benefits:8081
    depends_on:
      - mysql

  player-benefits-service:
    hostname: player-benefits
    image: player-benefits-service:0.0.1-SNAPSHOT
    container_name: player-benefits-service
    ports:
      - "8081:8081"
    environment:
      spring.aerospike.host: aerospike
    depends_on:
      - aerospike

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      PAYMENT_PAGE_URI: http://payment-page:8082

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_page

  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike
    ports:
      - "3000-3002:3000-3002"
    environment:
      NAMESPACE: payments
