spring:
  application:
    name: payment-page
  datasource:
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/payment_page

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082