spring:
  application:
    name: payment-page
  datasource:
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/payment_page

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
   readinessstate:
     enabled: true
   livenessstate:
     enabled: true
server:
  port: 8082