eureka:
  client:
    enabled: true
spring:
  application:
    name: payment-page
  boot:
    admin:
      client:
        enabled: false
  datasource:
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/payment_page
  cloud:
    loadbalancer:
      retry:
        max-retries-on-next-service-instance: 2
        max-retries-on-same-service-instance: 0
        retryable-status-codes: 500

feign:
  client:
    config:
      default:
        connectTimeout: 200
        readTimeout: 1000

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082


resilience4j:
  thread-pool-bulkhead:
    instances:
      getPlayerBenefits:
        maxThreadPoolSize: 50
        coreThreadPoolSize: 20
        queueCapacity: 1
  timelimiter:
    instances:
      getPlayerBenefits:
        timeoutDuration: 4s
        cancelRunningFuture: true
  circuitbreaker:
    instances:
      getPlayerBenefits:
        slidingWindowSize: 50
        minimumNumberOfCalls: 50
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 60s
        failureRateThreshold: 50