eureka:
  client:
    enabled: true
spring:
  application:
    name: payment-page
  boot:
    admin:
      client:
        enabled: false
  datasource:
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/payment_page

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082

resilience4j:
  retry:
    instances:
      getPlayerBenefits:
        maxRetryAttempts: 3
        retryExceptions:
          - feign.FeignException$FeignServerException