apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: default
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: eureka:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8761
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /actuator/health
              port: 8761
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /actuator/health
              port: 8761
          env:
            - name: eureka.instance.preferIpAddress
              value: "true"