apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: default
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /actuator/health
              port: 8080
          env:
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: eureka.client.serviceUrl.defaultZone
              value: "http://eureka:8761/eureka"