apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-benefits-service-deployment
  namespace: default
  labels:
    app: player-benefits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-benefits-service
  template:
    metadata:
      labels:
        app: player-benefits-service
    spec:
      containers:
        - name: player-benefits-service
          image: player-benefits-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8081
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
              path: /actuator/health/liveness
              port: 8081
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: 8081
          env:
            - name: spring.aerospike.host
              valueFrom:
                configMapKeyRef:
                  name: player-benefits-service-configmap
                  key: aerospike-host