server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: payment-page
          uri: ${PAYMENT_PAGE_URI}
          predicates:
            - Path=/payment-page/public/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
  application:
    name: gateway

management:
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,gateway