server:
  port: 8081
spring:
  application:
    name: player-benefits
  aerospike:
    host: localhost
    namespace: payments
    port: 3000

management:
  endpoints:
    web:
      exposure:
        include: '*'
