eureka:
  client:
    enabled: true
server:
  port: 8081
spring:
  application:
    name: player-benefits
  aerospike:
    host: localhost
    namespace: payments
    port: 3000
  boot:
    admin:
      client:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
