server:
  port: 8081
spring:
  application:
    name: player-benefits
  aerospike:
    host: localhost
    namespace: payments
    port: 3000

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
